export enum Event {
  // Authentication Events
  USER_REGISTERED = 'USER_REGISTERED',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILED = 'LOGIN_FAILED',
  LOGOUT = 'LOGOUT',

  // Email Verification Events
  EMAIL_VERIFIED = 'EMAIL_VERIFIED',
  EMAIL_VERIFICATION_FAILED = 'EMAIL_VERIFICATION_FAILED',
  OTP_RESENT = 'OTP_RESENT',

  // Password Events
  PASSWORD_RESET_REQUESTED = 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',

  // Security Events
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  ACCOUNT_UNLOCKED = 'ACCOUNT_UNLOCKED',
  SUSPICIOUS_ACTIVITY = 'SUSPICIOUS_ACTIVITY',
  DEVICE_TRUSTED = 'DEVICE_TRUSTED',
  DEVICE_REVOKED = 'DEVICE_REVOKED',

  // Token Events
  TOKEN_REFRESHED = 'TOKEN_REFRESHED',
  TOKEN_REVOKED = 'TOKEN_REVOKED',

  // Profile Events
  PROFILE_UPDATED = 'PROFILE_UPDATED',
  PROFILE_VIEWED = 'PROFILE_VIEWED',

  // Account Events
  ACCOUNT_DEACTIVATED = 'ACCOUNT_DEACTIVATED',
  ACCOUNT_REACTIVATED = 'ACCOUNT_REACTIVATED',
  ACCOUNT_DELETED = 'ACCOUNT_DELETED',

  SECURITY_ALERT_SENT = 'SECURITY_ALERT_SENT',
  FAILED_LOGIN_ALERT = 'FAILED_LOGIN_ALERT',
  ACCOUNT_LOCKED_ALERT = 'ACCOUNT_LOCKED_ALERT',
}
